version: '3.9'

services:
  api-service:
    container_name: api-container
    image: api-image-sample2
    ports:
      - '8888:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge